/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef, useState } from 'react';
import { useFrame } from '@react-three/fiber';

export default function Trex(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/Tyrannosaurus Rex.glb');

  useFrame(() => {
    group.current.rotation.y -= 0.01;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.01, 0.01, 0.01]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tyrannosaurus_rex1.geometry}
          material={nodes.tyrannosaurus_rex1.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Tyrannosaurus Rex.glb');
